sex(slava_smirnov, male).
sex(sveta_shevchuk, female).
sex(pavel_shevchuk, male).
sex(mariya_shevchuk, female).
sex(fedor_smirnov, male).
sex(lidia_smirnov, female).
sex(alexander_shevchuk, male).
sex(ludmila_shevchuk, female).
sex(svetlana_starodumova, female).
sex(yuiri_starodumov, male).
sex(yuiri_kuzmin, male).
sex(maria_bobrova, female).
sex(kate_kuzmina, female).
sex(alexander_kuzmin, male).
sex(alexey_bobrov, male).
sex(dmitryi_bobrov, male).
sex(anna_bobrova, female).
sex(artem_perepeluk, male).
sex(alexandra_perepeluk, female).
sex(nikolay_perepeluk, male).
sex(maria_kustova, female).
sex(vasil_stenberg, male).
sex(avgust_stenberg, male).
sex(maria_stenberg, female).
sex(anastasia_stenberg, female).
sex(vasiliy_stenberg, male).
sex(valentin_perepeluk, male).
sex(valentina_perepeluk, female).
sex(valeriy_perepeluk, male).
sex(konstantin_perepeluk, male).
sex(neonila_bocenko, female).
sex(mikhail_bocenko, male).
sex(igor_bocenko, male).
sex(sergei_bocenko, male).
sex(ivan_shevchuk, male).
sex(ekaterina_shevchuk, female).
sex(nikolay_shevchuk, male).
sex(vasiliy_shevchuk, male).
sex(vlad_shevchuk, male).
sex(valentina_shevchuk, male).
sex(gerasim_kulakov, male).
sex(georg_shevchuk, male).
sex(nadezhda_shevchuk, female).
sex(elena_shevchuk, female).
sex(sergei_shevchuk, male).
sex(grigoriy_smirnov, female).
sex(viktor_smirnov, male).
sex(natalya_smirnova, female).
sex(anna_shevchuk, female).
sex(nikola_shevchuk, male).
sex(vladimir_shevchuk, male).
sex(maria_shevchuk, female).
sex(serg_shevchuk, male).
sex(irina_shevchuk, female).
sex(deb_smirnov, male).
sex(egor_bessudnov, male).
sex(evdokia_smirnov, female).
sex(maksim_smirnov, male).
sex(olga_smirnov, female).
sex(pasha_smirnov, male).
sex(nikita_smirnov, male).
sex(denis_smirnov, male).
sex(mikhail_starodumov, male).
sex(tamara_starodumova, female).
sex(oleg_starodumov, male).
sex(svetlana_bobrova, female).
sex(anatoliy_bobrov, male).
sex(tatyana_bobrova, female).
sex(vladimir_chernov, male).
sex(nadezhda_chernova, female).
sex(marina_starodumova, female).
sex(lisa_starodumova, female).
sex(viktoria_starodumova, female).
sex(darya_starodumova, female).
sex(anya_starodumova, female).
sex(anya_shevchuk, female).
sex(evdokia_kulakova, female).
sex(sofia_perepeluk, female).
sex(elena_ishkina, female).
sex(valya_verova, female).
sex(dimon_shevchuk, male).
sex(yulia_verova, female).
parent(slava_smirnov, pavel_shevchuk).
parent(sveta_shevchuk, pavel_shevchuk).
parent(slava_smirnov, mariya_shevchuk).
parent(sveta_shevchuk, mariya_shevchuk).
parent(fedor_smirnov, slava_smirnov).
parent(lidia_smirnov, slava_smirnov).
parent(fedor_smirnov, maksim_smirnov).
parent(lidia_smirnov, maksim_smirnov).
parent(alexander_shevchuk, sveta_shevchuk).
parent(ludmila_shevchuk, sveta_shevchuk).
parent(alexander_shevchuk, svetlana_starodumova).
parent(ludmila_shevchuk, svetlana_starodumova).
parent(yuiri_starodumov, yuiri_kuzmin).
parent(svetlana_starodumova, yuiri_kuzmin).
parent(yuiri_starodumov, maria_bobrova).
parent(svetlana_starodumova, maria_bobrova).
parent(yuiri_kuzmin, alexander_kuzmin).
parent(kate_kuzmina, alexander_kuzmin).
parent(dmitryi_bobrov, alexey_bobrov).
parent(svetlana_bobrova, alexey_bobrov).
parent(dmitryi_bobrov, anna_bobrova).
parent(svetlana_bobrova, anna_bobrova).
parent(artem_perepeluk, ludmila_shevchuk).
parent(alexandra_perepeluk, ludmila_shevchuk).
parent(artem_perepeluk, valentin_perepeluk).
parent(alexandra_perepeluk, valentin_perepeluk).
parent(artem_perepeluk, neonila_bocenko).
parent(alexandra_perepeluk, neonila_bocenko).
parent(nikolay_perepeluk, artem_perepeluk).
parent(sofia_perepeluk, artem_perepeluk).
parent(vasil_stenberg, alexandra_perepeluk).
parent(maria_kustova, alexandra_perepeluk).
parent(vasil_stenberg, anastasia_stenberg).
parent(maria_kustova, anastasia_stenberg).
parent(vasil_stenberg, vasiliy_stenberg).
parent(maria_kustova, vasiliy_stenberg).
parent(avgust_stenberg, vasil_stenberg).
parent(maria_stenberg, vasil_stenberg).
parent(valentin_perepeluk, valeriy_perepeluk).
parent(valentina_perepeluk, valeriy_perepeluk).
parent(valentin_perepeluk, konstantin_perepeluk).
parent(valentina_perepeluk, konstantin_perepeluk).
parent(mikhail_bocenko, igor_bocenko).
parent(neonila_bocenko, igor_bocenko).
parent(mikhail_bocenko, sergei_bocenko).
parent(neonila_bocenko, sergei_bocenko).
parent(ivan_shevchuk, alexander_shevchuk).
parent(ekaterina_shevchuk, alexander_shevchuk).
parent(ivan_shevchuk, nikolay_shevchuk).
parent(ekaterina_shevchuk, nikolay_shevchuk).
parent(ivan_shevchuk, vasiliy_shevchuk).
parent(ekaterina_shevchuk, vasiliy_shevchuk).
parent(ivan_shevchuk, vlad_shevchuk).
parent(ekaterina_shevchuk, vlad_shevchuk).
parent(ivan_shevchuk, valentina_shevchuk).
parent(ekaterina_shevchuk, valentina_shevchuk).
parent(gerasim_kulakov, ekaterina_shevchuk).
parent(evdokia_kulakova, ekaterina_shevchuk).
parent(georg_shevchuk, ivan_shevchuk).
parent(anya_shevchuk, ivan_shevchuk).
parent(vasiliy_shevchuk, elena_shevchuk).
parent(nadezhda_shevchuk, elena_shevchuk).
parent(vasiliy_shevchuk, sergei_shevchuk).
parent(nadezhda_shevchuk, sergei_shevchuk).
parent(valentina_shevchuk, viktor_smirnov).
parent(grigoriy_smirnov, viktor_smirnov).
parent(valentina_shevchuk, natalya_smirnova).
parent(grigoriy_smirnov, natalya_smirnova).
parent(nikolay_shevchuk, nikola_shevchuk).
parent(anna_shevchuk, nikola_shevchuk).
parent(nikolay_shevchuk, vladimir_shevchuk).
parent(anna_shevchuk, vladimir_shevchuk).
parent(vlad_shevchuk, serg_shevchuk).
parent(maria_shevchuk, serg_shevchuk).
parent(vlad_shevchuk, irina_shevchuk).
parent(maria_shevchuk, irina_shevchuk).
parent(deb_smirnov, fedor_smirnov).
parent(evdokia_smirnov, fedor_smirnov).
parent(egor_bessudnov, lidia_smirnov).
parent(elena_ishkina, lidia_smirnov).
parent(maksim_smirnov, pasha_smirnov).
parent(olga_smirnov, pasha_smirnov).
parent(maksim_smirnov, nikita_smirnov).
parent(olga_smirnov, nikita_smirnov).
parent(maksim_smirnov, denis_smirnov).
parent(olga_smirnov, denis_smirnov).
parent(mikhail_starodumov, yuiri_starodumov).
parent(tamara_starodumova, yuiri_starodumov).
parent(mikhail_starodumov, oleg_starodumov).
parent(tamara_starodumova, oleg_starodumov).
parent(anatoliy_bobrov, dmitryi_bobrov).
parent(tatyana_bobrova, dmitryi_bobrov).
parent(vladimir_chernov, svetlana_bobrova).
parent(nadezhda_chernova, svetlana_bobrova).
parent(oleg_starodumov, lisa_starodumova).
parent(marina_starodumova, lisa_starodumova).
parent(oleg_starodumov, viktoria_starodumova).
parent(marina_starodumova, viktoria_starodumova).
parent(oleg_starodumov, darya_starodumova).
parent(marina_starodumova, darya_starodumova).
parent(oleg_starodumov, anya_starodumova).
parent(marina_starodumova, anya_starodumova).
parent(vladimir_shevchuk, dimon_shevchuk).
parent(valya_verova, dimon_shevchuk).
parent(vladimir_shevchuk, yulia_verova).
parent(valya_verova, yulia_verova).
